### ISSUE TITLE
manus.py ignorerer ikke udkommenterede ting

### ISSUE THREAD

**Issue by ptcher** [TK-IT/revypython#10]
Når vi genererer det endelige manus kan vi ikke bare udkommentere ting i TeX'en for at checke revyens running time. Det er nok fordi parseren ikke ignorerer linjer der starter med "%".

**Comment by Mortal** [comment]
Jeg er på telefonen, men tilføj følgende linje til MACROS og det burde bare
virke:
('comment', r'%.*'),

Det håndterer dog ikke escapede procenttegn.
